name: Clean abandoned branches

on:
  # At 01:00 on day-of-month 15 in every 3rd month
  schedule:
    - cron: '0 1 15 */3 *'

  # Allow workflow to be manually run from the GitHub UI
  workflow_dispatch:

jobs:
  cleanup_old_branches:
    runs-on: ubuntu-latest
    steps:
      - name: Delete those pesky dead branches
        uses: phpdocker-io/github-actions-delete-abandoned-branches@v1
        with:
          github_token: ${{ github.token }}
          last_commit_age_days: 90
          ignore_branches: dev,main
          dry_run: no
